FROM node:14.5.0-alpine as builder

ENV HOME=/home/medfasee

RUN mkdir -p $HOME/frontend

WORKDIR $HOME/frontend

RUN apk add --no-cache bash

COPY package.json yarn.lock ./

RUN yarn

COPY . $HOME/frontend

RUN apk --no-cache add curl

RUN yarn build

FROM nginx:latest as production-stage
COPY --from=builder /home/medfasee/frontend/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]